dynamixel/position/inicial: 0
dynamixel/position/final: 185
dynamixel/speed/measuring: 50
dynamixel/speed/positioning: 50
dynamixel/portUSB/number: 1

hokuyo/angulo/maximo: 225
hokuyo/angulo/minimo: 45
hokuyo/rango/maximo: 60000
hokuyo/rango/minimo: 210
hokuyo/portACM/number: 0
